# # training_data = [
# #     {'track_id': '1bDbXMyjaUIooNwFE9wn0N', 'emotion': 'Joy'},
# #     {'track_id': '3azJifCSqg9fRij2yKIbWz', 'emotion': 'Anticipation'},
# #     {'track_id': '3JsydWaf2Ev4ehaLUjj3SY', 'emotion': 'Joy'},
# #     {'track_id': '7z3PblAN3dH1JMewiRydkZ', 'emotion': 'Trust'},
# #     {'track_id': '3B4cjvGlPvyBLNG3AzEgkZ', 'emotion': 'Joy'},
# #     {'track_id':'514joG57v4yKTsfQmz7stz', 'emotion': 'Anger'},
# #     {'track_id': '7sVbKoBdhXtYCEOO6qC1SN', 'emotion': 'Anticipation'},
# #     {'track_id': '2xFg6AyHkXFruGxRjy7Uzn','emotion': 'Anticipation'},
# #     {'track_id': '3ExgWVPWOQts9RVBkqpdic', 'emotion': 'Joy'},
# #     {'track_id': '03auLpFLdCv4HozP4pQseu', 'emotion': 'Trust'},
# #     {'track_id': '2LgrNOU8GQYASgz7lIDVt3', 'emotion': 'Anger'},
# #     {'track_id': '4YmsnZcxHEGEqHB3K0vdt0', 'emotion': 'Anticipation'},
# #     {'track_id': '4Dvkj6JhhA12EX05fT7y2e', 'emotion': 'Joy'},
# #     {'track_id': '7npLlaPu9Mfno8hjk5OagD', 'emotion': 'Trust'},
# #     {'track_id': '7JJmb5XwzOO8jgpou264Ml', 'emotion': 'Joy'},
# #     {'track_id': '0tgVpDi06FyKpA1z0VMD4v', 'emotion': 'Joy'},
# #     {'track_id': '4nVBt6MZDDP6tRVdQTgxJg', 'emotion': 'Anticipation'},
    

# # ]

# training_data = [
#     {'track_name': 'Runnin', 'emotion': 'Anticipation'},
#     {'track_name': 'ALL THE LOVE (feat. Andre Troutman)', 'emotion': 'Trust'},
#     {'track_name': 'Empire State Of Mind', 'emotion': 'Joy'},
#     {'track_name': 'On Top', 'emotion': 'Anger'},
#     {'track_name': 'KICK OUT', 'emotion': 'Anger'},
#     {'track_name': 'Naal Nachna', 'emotion': 'Anticipation'},
#     {'track_name': 'Tum Hi Ho Bandhu', 'emotion': 'Joy'},
#     {'track_name': 'Ok Jaanu Title Track', 'emotion': 'Trust'},
#     {'track_name': 'Shararat (From "Dhurandhar")', 'emotion': 'Surprise'},
#     {'track_name': 'Lutt Le Gaya', 'emotion': 'Joy'},
#     {'track_name': 'Let Me Love You', 'emotion': 'Joy'},
#     {'track_name': 'You Belong With Me (Taylor’s Version)', 'emotion': 'Anticipation'},
#     {'track_name': 'Sure Thing - Sped Up', 'emotion': 'Trust'},
#     {'track_name': "we can't be friends (wait for your love)", 'emotion': 'Fear'},
#     {'track_name': 'One Kiss (with Dua Lipa)', 'emotion': 'Joy'},
#     {'track_name': 'Nonsense', 'emotion': 'Trust'},
#     {'track_name': '7 rings', 'emotion': 'Anticipation'},
#     {'track_name': 'Toxic', 'emotion': 'Surprise'},
#     {'track_name': 'Cruel Summer', 'emotion': 'Anticipation'},
#     {'track_name': 'Tangerine', 'emotion': 'Joy'},
#     {'track_name': 'Blank Space', 'emotion': 'Trust'},
#     {'track_name': 'Levitating (feat. DaBaby)', 'emotion': 'Joy'},
#     {'track_name': 'Side To Side', 'emotion': 'Fear'},
#     {'track_name': 'greedy', 'emotion': 'Fear'},
#     {'track_name': 'Runaway', 'emotion': 'Fear'},
#     {'track_name': 'Confident', 'emotion': 'Trust'},
#     {'track_name': 'BURN', 'emotion': 'Joy'},
#     {'track_name': "DON'T KILL THE PARTY (feat. Quavo & Juicy J)", 'emotion': 'Anticipation'},
#     {'track_name': 'GIRLS', 'emotion': 'Surprise'},
#     {'track_name': 'ATM', 'emotion': 'Anticipation'},
#     {'track_name': 'Bad Bad Bad (feat. Lil Baby)', 'emotion': 'Joy'},
#     {'track_name': 'TORE UP', 'emotion': 'Anger'},
#     {'track_name': 'FATHER (feat. Travis Scott)', 'emotion': 'Anger'},
#     {'track_name': 'Boyfriend', 'emotion': 'Joy'},
#     {'track_name': 'Stitches', 'emotion': 'Fear'},
#     {'track_name': 'Happier', 'emotion': 'Fear'},
#    # {'track_name': 'Ghost', 'emotion': 'Sadness'},
#     {'track_name': 'Riptide', 'emotion': 'Fear'},
#     {'track_name': 'Ordinary', 'emotion': 'Trust'},
#     {'track_name': "There's Nothing Holdin' Me Back", 'emotion': 'Joy'},
#     {'track_name': 'Nice To Meet You', 'emotion': 'Surprise'},
#     {'track_name': 'Stargazing', 'emotion': 'Anticipation'},
#     {'track_name': 'Ghost Town', 'emotion': 'Anticipation'},
#     {'track_name': 'I Really Do...', 'emotion': 'Joy'}
# ]
training_data = [
    {"track_name": "greedy", "emotion": "Energetic"},
    {"track_name": "Stitches", "emotion": "Happy"},
    {"track_name": "Into You", "emotion": "Happy"},
    {"track_name": "No Lie", "emotion": "Happy"},
    {"track_name": "Strawberries & Cigarettes", "emotion": "Mellow"},
    {"track_name": "Cruel Summer", "emotion": "Mellow"},
    {"track_name": "CHANEL", "emotion": "Energetic"},
    {"track_name": "We Still Don't Trust You", "emotion": "Energetic"},
    {"track_name": "Runnin", "emotion": "Energetic"},
    {"track_name": "ALL THE LOVE", "emotion": "Energetic"},
    {"track_name": "Empire State of Mind", "emotion": "Mellow"},
    {"track_name": "On Top 2", "emotion": "Energetic"},
    {"track_name": "KICK OUT", "emotion": "Energetic"},
    {"track_name": "Naal Nachna", "emotion": "Mellow"},
    {"track_name": "Tum Hi Ho Bandhu", "emotion": "Happy"},
    {"track_name": "Shararat", "emotion": "Mellow"},
    {"track_name": "Lutt Le Gaya", "emotion": "Energetic"},
    {"track_name": "Let Me Love You", "emotion": "Energetic"},
    {"track_name": "You Belong With Me (Taylor's Version)", "emotion": "Happy"},
    {"track_name": "Sure Thing (Sped Up)", "emotion": "Mellow"},
    {"track_name": "we can't be friends (wait for your love)", "emotion": "Happy"},
    {"track_name": "One Kiss", "emotion": "Happy"},
    {"track_name": "Nonsense", "emotion": "Happy"},
    {"track_name": "7 rings", "emotion": "Mellow"},
    {"track_name": "Toxic", "emotion": "Mellow"},
    {"track_name": "Tangerine (feat. Arlo Parks)", "emotion": "Happy"},
    {"track_name": "Blank Space", "emotion": "Happy"},
    {"track_name": "Levitating (feat. DaBaby)", "emotion": "Energetic"},
    {"track_name": "Runaway", "emotion": "Happy"},
    {"track_name": "Confident (feat. Chance The Rapper) [Single Version]", "emotion": "Happy"},
    {"track_name": "BURN", "emotion": "Energetic"},
    {"track_name": "DON'T KILL THE PARTY (feat. Quavo & Juicy J)", "emotion": "Energetic"},
    {"track_name": "GIRLS", "emotion": "Energetic"},
    {"track_name": "ATM", "emotion": "Energetic"},
    {"track_name": "Bad Bad Bad (feat. Lil Baby)", "emotion": "Mellow"},
    {"track_name": "TORE UP", "emotion": "Energetic"},
    {"track_name": "FATHER (feat. Travis Scott)", "emotion": "Energetic"},
    {"track_name": "Boyfriend", "emotion": "Happy"},
    {"track_name": "Happier", "emotion": "Happy"},
    {"track_name": "Ghost", "emotion": "Mellow"},
    {"track_name": "Riptide", "emotion": "Mellow"},
]